name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup: Checkout'
        uses: actions/checkout@v3.1.0

      - name: 'Setup: Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Setup: Cache'
        uses: actions/cache@v3.0.11
        with:
          path: ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Setup: Install dependencies'
        run: yarn install --frozen-lockfile

      - name: 'Quality: ESlint'
        run: yarn lint

      - name: 'Build: run dist build'
        run: yarn build && yarn export

      - name: 'Deploy: FTP deployment'
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: wp10663825.server-he.de
          username: ftp10663825-chris
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: www/
          local-dir: 'out/'
          dangerous-clean-slate: false
